"""
Django settings for ATTN_Django project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g#7&gv)e=qeaw^98wk#0q-4rn#4!rz)jcx$vdn0ep+_y3%o@m2'

# SECURITY WARNING: don't run with debug turned on in production!
import os
import environ
import dj_database_url
from pathlib import Path

# 1. Define BASE_DIR first so 'environ' knows where to look for .env
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# 3. Read the .env file
# This looks for a file named .env in your root project folder
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 4. Security Settings (Pulled from .env)
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

# 5. Allowed Hosts (Crucial for publishing)
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.railway.app', '.vercel.app']

# 6. Database Configuration (Pulled from .env)
DATABASES = {
    'default': dj_database_url.config(
        default=env('SUPABASE_DB_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}

ALLOWED_HOSTS = ["*", "10.190.119.125", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'ATTN_Backend',
    'rest_framework',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'ATTN_Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ATTN_Django.wsgi.application'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# In settings.py
DATABASES = {
    'default': dj_database_url.config(
        # This tells Django: "Use the URL in my .env file. 
        # If that's missing, use my local postgres."
        default=env('SUPABASE_DB_URL', default='postgres://postgres:1234@127.0.0.1:5432/attn_db'),
        conn_max_age=600,
        ssl_require=True if not DEBUG else False
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR.parent / "static",   # 👈 one level up from Herencia_Django
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

