# Generated by Django 5.2.8 on 2025-11-29 15:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('USER_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('USERNAME', models.CharField(max_length=255, unique=True)),
                ('DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('PASSWORD', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ATTN_Backend_accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('EWALL_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EWALL_APP', models.CharField(max_length=255)),
                ('EWALL_TYPE', models.CharField(max_length=255)),
                ('EWALL_DATE', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('EWALL_ACC_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('EWAL_NUM', models.CharField(blank=True, max_length=255, null=True)),
                ('EWALL_AMOUNT', models.BigIntegerField(blank=True, null=True)),
                ('EWALL_FEE', models.BigIntegerField(blank=True, null=True)),
                ('EWALL_TOTAL', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ATTN_Backend_ewallet',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('cus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_num', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amt', models.FloatField()),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionList',
            fields=[
                ('trans_list_id', models.BigAutoField(db_column='TRANS_LIST_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ATTN_Backend_transaction_list',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ATTN_Backend.orderproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATTN_Backend.category')),
            ],
            options={
                'db_table': 'ATTN_Backend_product',
            },
        ),
        migrations.CreateModel(
            name='TransactionLists',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('cus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_num', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amt', models.FloatField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATTN_Backend.orderproducts')),
            ],
        ),
    ]
