# Generated by Django 5.2.8 on 2025-11-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATTN_Backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionList',
        ),
        migrations.DeleteModel(
            name='TransactionLists',
        ),
    ]
