# Generated by Django 5.2.8 on 2025-11-29 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTN_Backend', '0002_delete_transactionlist_delete_transactionlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
