# Generated by Django 5.2.6 on 2026-04-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTN_Backend', '0003_orderproducts_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='price',
        ),
        migrations.CreateModel(
            name='DebtPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ATTN_Backend.orderproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock Warning'), ('out_of_stock', 'Out of Stock Alert'), ('restock_soon', 'Restock Soon')], max_length=20)),
                ('message', models.TextField()),
                ('days_until_stockout', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATTN_Backend.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
